<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <EnableNUnitRunner>true</EnableNUnitRunner>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="ProtonBlazor.UnitTests.Shared" />
    <Using Include="ProtonBlazor.UnitTests.Shared.Mocks" />
    <Using Include="ProtonBlazor.UnitTests.Shared.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.MTP" Version="10.0.1" />
    <PackageReference Include="JunitXml.TestLogger" Version="8.0.0" />
    <PackageReference Include="AwesomeAssertions" Version="9.4.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="1.1.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzer.Testing" Version="1.1.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing" Version="1.1.4" />
    <PackageReference Include="Microsoft.Testing.Extensions.HangDump" Version="2.2.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProtonBlazor.Analyzers.TestComponents\ProtonBlazor.Analyzers.TestComponents.csproj" />
    <ProjectReference Include="..\ProtonBlazor.Analyzers\ProtonBlazor.Analyzers.csproj">
      <!-- Some namespaces are matching with the core, we must use alias -->
      <Aliases>ProtonBlazorAnalyzer</Aliases>
    </ProjectReference>
    <ProjectReference Include="..\ProtonBlazor.Analyzers.CodeFixes\ProtonBlazor.Analyzers.CodeFixes.csproj">
      <Aliases>ProtonBlazorAnalyzer</Aliases>
    </ProjectReference>
    <ProjectReference Include="..\ProtonBlazor.UnitTests.Shared\ProtonBlazor.UnitTests.Shared.csproj" />
  </ItemGroup>

</Project>
