name: deploy-protonblazor-HEAD

on:
  workflow_dispatch:

jobs:
  deploy-web-app:
    name: Deploy HEAD to web app to protonblazor.com
    if: ${{ github.repository_owner == 'ProtonBlazor' }}
    uses: ProtonBlazor/Workflows/.github/workflows/template-deploy-web-app.yml@main
    with:
      web-app-name: protonblazor
      web-app-slot-name:  'staging'
      swap-slots: true
      project-directory: ./src/ProtonBlazor.Docs.WasmHost
    secrets:
      publish-profile: ${{ secrets.PUBLISH_PROTONBLAZOR }}
      azure-cred: ${{ secrets.AZURE_CREDENTIALS_MUD_PROD }}
